services:
  - type: web
    name: product-management
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn goods.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: goods.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
    staticPublishPath: staticfiles
